# Generated by Django 4.2.2 on 2023-07-02 07:58

from django.db import migrations, models
import twoD.models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0005_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='ampm',
            field=models.CharField(default=twoD.models.getAmPm, max_length=3),
        ),
    ]
