# Generated by Django 4.2.2 on 2023-07-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0007_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='session',
        ),
    ]
