# Generated by Django 4.2.2 on 2023-07-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0008_remove_value_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='transfer',
        ),
        migrations.AddField(
            model_name='value',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
