# Generated by Django 4.2.2 on 2023-07-02 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0009_remove_value_transfer_value_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('com_rate', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommissionUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommUser', to='twoD.commission')),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LogNum', to='twoD.number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LogUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
