# Generated by Django 4.2.2 on 2023-07-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0010_commission_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='comm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommUser', to='twoD.commission'),
        ),
    ]
