# Generated by Django 4.2.2 on 2023-07-05 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0011_alter_log_comm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveNumLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArchiveNumLogComm', to='twoD.commission')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('archiveLog', models.ManyToManyField(related_name='archive_logs', to='twoD.archivenumlog')),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArchiveNumNum', to='twoD.number')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('transfer', models.IntegerField()),
                ('archiveNum', models.ManyToManyField(related_name='ArchiveNums', to='twoD.archivenum')),
                ('jp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArchiveJP', to='twoD.number')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArchiveSession', to='twoD.seccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArchiveUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
