# Generated by Django 4.2.2 on 2023-07-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0012_archivenumlog_archivenum_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='jp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArchiveJP', to='twoD.number'),
        ),
    ]
