# Generated by Django 4.2.2 on 2023-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0013_alter_archive_jp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivenum',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
