# Generated by Django 4.2.2 on 2023-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0014_alter_archivenum_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivenumlog',
            name='commRate',
            field=models.IntegerField(default=0),
        ),
    ]
