# Generated by Django 4.2.2 on 2023-07-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0015_archivenumlog_commrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivenumlog',
            name='commRate',
            field=models.FloatField(default=0),
        ),
    ]
